/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package IdCheck.UI;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pervac
 */
public class PersonalForm extends javax.swing.JFrame {
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Imagen", "jpg");
    private String Rutafoto;
    
    
    /**
     * Creates new form PersonalForm
     */
    public PersonalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cmdCondicionP = new javax.swing.JComboBox();
        cmbCargo = new javax.swing.JComboBox();
        cmbEmpresa = new javax.swing.JComboBox();
        btnInsertarFoto = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Condicion de la Persona:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, -1));
        getContentPane().add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, -1));

        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setText("Cargo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtDNI.setToolTipText("");
        txtDNI.setName("txtDNI"); // NOI18N
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 300, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 300, -1));

        cmdCondicionP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmdCondicionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 300, -1));

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 300, -1));

        cmbEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 300, -1));

        btnInsertarFoto.setText("Insertar Foto");
        btnInsertarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon("D:\\1 - INGENIERIAS\\trabajo final control de acceso po codigo de barras\\Repositorios ID check\\ID Check\\IDCheck\\Iconos\\24x24\\actions\\document-save-as.png")); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon("D:\\1 - INGENIERIAS\\trabajo final control de acceso po codigo de barras\\Repositorios ID check\\ID Check\\IDCheck\\Iconos\\24x24\\actions\\add.png")); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        lblFoto.setBackground(new java.awt.Color(0, 0, 0));
        lblFoto.setText("Imagen");
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
        });
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 110, 160));

        jLabel8.setText("Empresa:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void btnInsertarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFotoActionPerformed
        
//creamos un objeto de JFILECHOOSER para que se abra una ventada de exploracion de archivos
        JFileChooser dlg = new JFileChooser();
        //del objeto creado llamados al metodo setFileFilter para que solo busque archivos con extension .jpg
        dlg.setFileFilter(filter);
        //Abre la ventana de dialogo
        int option = dlg.showOpenDialog(this);
        //Si hace click en el boton abrir del dialogo
        if (option == JFileChooser.APPROVE_OPTION) {
            //Obtiene nombre del archivo seleccionado
            String fil = dlg.getSelectedFile().getPath();
            //se obtiene la direccion donde se guardara la imagen
            String file = dlg.getSelectedFile().toString();
            lblFoto.setIcon(new ImageIcon(fil));
            //Modificando la imagen
            ImageIcon icon = new ImageIcon(fil);
            //Se extrae la imagen del icono
            Image img = icon.getImage();
            //Se modifica su tamaño
            Image newimg = img.getScaledInstance(155, 175, java.awt.Image.SCALE_SMOOTH);
            //SE GENERA EL IMAGE ICON CON LA NUEVA IMAGEN
            ImageIcon newIcon = new ImageIcon(newimg);
            //Se coloca el nuevo icono modificado
            lblFoto.setIcon(newIcon);
            //Se cambia el tamaño de la etiqueta
            lblFoto.setSize(155, 175);
            //TXTRUTAFOTO.setText(fil);
            Rutafoto =  fil;
        }     
//seletamos la variable local con la ruta de la imagen
    }//GEN-LAST:event_btnInsertarFotoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        if (Rutafoto.length() == 0) {
            JOptionPane.showMessageDialog(null, "FALTA SUBIR FOTO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
        } else {
            //ruta del archivo de imagen
            String g = Rutafoto;
            
           FileInputStream fis =null;
           
            try {
                File file = new File(g);
                fis = new FileInputStream(file);
                try (
                    PreparedStatement pstm = con.getConnection().prepareStatement("{call INSERTARDOCENTE (?,?,?,?,?,?,?)}")) {
                    pstm.setString(1, TXTDNI.getText());
                    pstm.setString(2, TXTNOMBRED.getText());
                    pstm.setString(3, TXTAPELLIDOP.getText());
                    pstm.setString(4, TXTAPELLIDOM.getText());
                    pstm.setString(5, TXTCELUNAR.getText());
                    pstm.setString(6, TXTCORREO.getText());
                    //convertirlo a binarios
                    pstm.setBinaryStream(7, fis, (int) file.length());
                    ResultSet r = pstm.executeQuery();
                    String respuesta = "";
                    while (r.next()) {
                        respuesta = r.getString(1).toString();
                    }
                    JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);
                    //falta metodo cargardocente, limpiar,FormatoDocente                       
                    ocultamensaje();
                    TXTFOTO.setIcon(new ImageIcon(getClass().getResource("/Imagenes/guji.png")));
                }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON LOS ARCHIVOS REQUERIDOS PARA EL REGISTRO DEL DOCENTE", "ERROR", JOptionPane.WARNING_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
            } finally {
                try {
                    fis.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL MOMENTO DE CERRAR LA CONEXION CON LA BASE DE DATOS", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFotoMouseClicked
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and displbtnInsertarFotoorm */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsertarFoto;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbCargo;
    private javax.swing.JComboBox cmbEmpresa;
    private javax.swing.JComboBox cmdCondicionP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
